### ISSUE TITLE
app for listening to live music concerts archived in archive.org that uses service workers and push

### ISSUE THREAD

**Issue by dbialer** [mozilla/wadi#12]
Create a reference app that will allow you to listen to streaming music, download tracks and save them, create a playlist, share the music, and be notified when a new concert is available from your favorite artist.  From the public non-profit library of millions of free books, movies, software, music, and more.   It has the largest (and only) collection of Grateful Dead concerts among other treasures ( (also String Cheese, Cracker, Phil Lesh, John Mayer, Jack Johson, Ryan Adams, and many new music of all tastes). And it is legal free music.

There is an Android app, Vibevault (GPL3) https://play.google.com/store/apps/details?id=com.code.vibevault  and code archived here: https://code.google.com/archive/p/vibevault/.  It allows you to do the above (except share and notifications).  

One of the interesting things it does is download a list of artists in the background and cache it on the device.  This seems like a good job for a service worker (as well as downloading in the background). 

Archive.org has a API here: https://archive.org/help/json.php

I can product manage this as I love the Android version of this app.

**Comment by mykmelez** [comment]
> Create a reference app that will allow you to listen to streaming music, download tracks and save them, create a playlist, share the music, and be notified when a new concert is available from your favorite artist. From the public non-profit library of millions of free books, movies, software, music, and more. It has the largest (and only) collection of Grateful Dead concerts among other treasures ( (also String Cheese, Cracker, Phil Lesh, John Mayer, Jack Johson, Ryan Adams, and many new music of all tastes). And it is legal free music.

Indeed, it looks like an extensive (albeit motley) collection! https://archive.org/details/audio

> There is an Android app, Vibevault (GPL3) https://play.google.com/store/apps/details?id=com.code.vibevault and code archived here: https://code.google.com/archive/p/vibevault/. It allows you to do the above (except share and notifications).

Vibe Vault's code could be helpful, although I'd chat with licensing folks about the implications of reusing GPL3-licensed code before looking at that codebase.

> One of the interesting things it does is download a list of artists in the background and cache it on the device. This seems like a good job for a service worker (as well as downloading in the background).

Right, there's potential here to demonstrate all three use cases that are commonly ascribed to Service Workers: offline, push, and background sync.

> I can product manage this as I love the Android version of this app.

Since Vibe Vault doesn't have sharing and notifications, perhaps there is an MVP that supports a subset of the features you've listed? I'm interested to hear your thoughts on what the key feature set of such an app would be, since there may be quite a bit of work to do here just to get the core functionality (i.e. downloading/caching/playing audio) to work. Although we may be able to reuse code from the High Fidelity podcast app to jumpstart that work.
