### ISSUE TITLE
create a cloud service for porting firefox os packaged apps to sw-precache

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#13]
It would be a small matter of programming to take a Firefox OS packaged app, parse it, generate a list of assets, and run sw-precache over that list.

**Comment by delapuente** [comment]
Quite similar to what [appmaker](http://test-appmaker.tid.es/) was doing (with appcache by the present moment).

**Comment by mykmelez** [comment]
This is an intriguing idea. In theory, it could expose those apps to a much larger audience (i.e. the whole web). It might also help FxOS developers implement support for Service Workers, since it would provide a test base of apps that should work just as well (when hosted and offlined via Service Workers) as they did (when packaged and installed).

Before embarking on a project like this, I'd want to know how many (and which) FxOS packaged apps would qualify for this transmogrification, because they don't require any special privileges (including system XHR) nor have any other peculiarities that are ill-supported by the standard Web platform.

Also, I wouldn't make this sw-precache specific. That's only one of the tools that we could use to implement something like this. It may or may not be the best one for this particular job, but that's an implementation detail that I would leave to the technician leading the effort.

> Quite similar to what appmaker was doing (with appcache by the present moment).

It's similar, but it isn't exactly the same, since (as I understand it) that project was designed to attract native app developers to develop new apps for the web platform, whereas this project is designed to "mop up" the residual value of existing packaged apps by making them available for the web platform (without encouraging developers to develop new apps, which should be developed directly for the web).

**Comment by delapuente** [comment]
> It's similar, but it isn't exactly the same, since (as I understand it) that project was designed to attract native app developers to develop new apps for the web platform, whereas this project is designed to "mop up" the residual value of existing packaged apps by making them available for the web platform (without encouraging developers to develop new apps, which should be developed directly for the web).

Yep but, correct me if I'm wrong @wfwalker , Dani was requesting the same info from Marketplace in order to possibly offer the service inside the market like a one-click convert-into-webapp feature.
