### ISSUE TITLE
can we do something special when serviceworker caches asm.js files?

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wadi#18]
Fabrice added code to Firefox OS app install flow to precompile asm.js files at app install time:
https://bugzilla.mozilla.org/show_bug.cgi?id=965970

Is there something equivalent we could/should do for games that cache their JS using SW?

**Comment by mykmelez** [comment]
The PluotSorbet developers chatted a bit with some SpiderMonkey hackers about doing something similar for Java files that PluotSorbet compiles to JavaScript, but I don't recall what we concluded about its feasibility. cc: @marco-c and @brendandahl in case they remember.

**Comment by marco-c** [comment]
I believe scripts are compiled as soon as loaded and the compilation is cached if they're big enough.
I don't know how the installation flow is supposed to work in the future, with the "progressive" apps. If the Chrome approach is taken (you use the app and then you can decide to install it), then we don't need to precompile because the scripts would be already compiled.

**Comment by wfwalker** [comment]
OK. I spoke with @lukewagner this week, and I think he was telling me there would be even less to do when WebAssembly comes along, so probably we can close this?

**Comment by lukewagner** [comment]
FWIW, I think there are some cool opportunities to make caching more efficient:
- attach the asm.js cache entry to the Response cached by the Cache API so that, on cache hit, we don't even have to look at the asm.js/wasm code, we jump straight to the cache hit path
- if a SW is preemptively streaming in asm.js/wasm code, it'd be cool to precompile it (analogous to `precompile`).  Maybe we could trigger this precompilation automatically when storing a Response into the Cache object?  It's harder for asm.js b/c we don't want to have to scan every JS file for "use asm", but for wasm it's easy to know it's wasm immediately and precompile it.
